development:
  clients:
    default:
      database: sssm_development
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: sssm
      hosts:
        - localhost:27017